### PR TITLE
Compatibility with web book and viz

### PR DESCRIPTION
**Pull request by mredaelli**
The changes introduced since the fork have removed some globals from the export, so that the visualization doesn't work anymore.

Here those are restored, and the new functions that were added are scoped elsewhere, to keep things clean.

I also pinned the dependencies to versions that do not require patching.

However, one problem remains: the satisfia mdp constructor returns an object that doesn't have all the fields that a world and an mdp usually have in the webppl world.
I tried returning somerthing like `_.assign({ new fields }, original_object)`, but when I do that computations fail (In computing `V` the library complains that an element of a vector is negative).

We should find out why that is, and return a proper object from `VerySimpleGW`. Right now I went around it by returning also the original `world`, so that the `draw` functions knows what to paint.

### CODE REVIEW

**Comment by mredaelli** [comment]
@v1ta111 please can you also take a look here?

My intention was to make things easy: now you clone, run `npm install`, and all should work: no need for a global `webppl`, install this, patch that. In fact, I added the pipeline to run in gitlab actions and it seems to work.

But there's always the possibility that it messes up with your setup.

**Comment by mredaelli** [comment]
Oh, I forgot: is this repo supposed to show the gridworld also *outside* the browser somehow, with Node.js opening a OS window etc?

From the deps in the precious `package.json` I would think so, but the `draw` function explicitly bails if it's not inside a wpp editor, and I didn't see examples that do that. So I removed most dependencies.

Let me know if I missed it

**Comment by mensch72** [comment]
> Oh, I forgot: is this repo supposed to show the gridworld also _outside_ the browser somehow, with Node.js opening a OS window etc?
> 
> From the deps in the precious `package.json` I would think so, but the `draw` function explicitly bails if it's not inside a wpp editor, and I didn't see examples that do that. So I removed most dependencies.
> 
> Let me know if I missed it

i don't see a need for that right now. main purpose is really to have a light-weight playful intro to our concepts on the web.

**Comment by mensch72** [comment]
> We should find out why that is, and return a proper object from `VerySimpleGW`. Right now I went around it by returning also the original `world`, so that the `draw` functions knows what to paint.

i'll try to devote some time on this but i agree your workaround is ok for now.

**Review by mensch72 — COMMENTED** [review]
Running `npm install` in my existing installation gives
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated domexception@1.0.1: Use your platform's native DOMException instead
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.

added 52 packages, removed 498 packages, changed 31 packages, and audited 196 packages in 25s

9 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (5 moderate, 1 critical)
```
which seems fine for now. 

Then doing `./run.sh examples/runVerySimpleGW.wppl -- --gw GW3 --verbose` also looks fine. 

Will look at the code next...

**Review by mensch72 — APPROVED** [review]
i don't see any issues, so let's merge

**Pull request merged**
